apiVersion: apps/v1
kind: Deployment
metadata:
    labels:
        app: app-1-system-mn2vvk
    name: app-1-system-mn2vvk-deploy
    namespace: wxm-test
spec:
    replicas: 1
    selector:
        matchLabels:
            app: app-1-system-mn2vvk
    template:
        metadata:
            labels:
                app: app-1-system-mn2vvk
                deployId: "400"
        spec:
            containers:
                - image: docker.io/wangxiamei/log:07031636
                  imagePullPolicy: Always
                  name: app-1-system-mn2vvk
                  command:
                    - /root/app
                  resources:
                    limits:
                        cpu: 1
                        memory: 2000Mi
                    requests:
                        cpu: 0.1
                        memory: 100Mi
            imagePullSecrets:
                - name: app-1-system-mn2vvk-secret
            restartPolicy: Always
