apiVersion: apps/v1
kind: Deployment
metadata:
    labels:
        app: app-1-system-mn2vvk
    name: app-1-system-mn2vvk-deploy
    namespace: dev
spec:
    replicas: 1
    selector:
        matchLabels:
            app: app-1-system-mn2vvk
    template:
        metadata:
            labels:
                app: app-1-system-mn2vvk
        spec:
            containers:
                - image: docker.io/wangxiamei/e-flow:20230529114837546
                  imagePullPolicy: IfNotPresent
                  name: app-1-system-mn2vvk
                  resources:
                    limits:
                        cpu: 1
                        memory: 2000Mi
                    requests:
                        cpu: 0.1
                        memory: 100Mi
            imagePullSecrets:
                - name: app-1-system-mn2vvk-secret
            restartPolicy: Always
