apiVersion: v1
kind: Service
metadata:
  name: app-1-system-mn2vvk-service
  namespace: dev
  labels:
    service: app-1-system-mn2vvk
spec:
  selector:
    app: app-1-system-mn2vvk
  type: NodePort
  ports:
    - name: app-1-system-mn2vvk-port
      protocol: TCP
      port: 80
      targetPort: 80
    - name: port2
      protocol: UDP
      port: 8080
      targetPort: 8080
    - name: port3
      protocol: TCP
      port: 9090
      targetPort: 9090
    - name: port4
      protocol: TCP
      port: 8081
      targetPort: 8081
      
